"""added on delete casade to foreign keys

Revision ID: 0722945f79ea
Revises: bb3a61472a4f
Create Date: 2022-12-31 21:41:56.186743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0722945f79ea'
down_revision = 'bb3a61472a4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('active', sa.Boolean(), nullable=False))
    op.drop_constraint('pooling_car_id_fkey', 'pooling', type_='foreignkey')
    op.drop_constraint('pooling_driver_id_fkey', 'pooling', type_='foreignkey')
    op.create_foreign_key(None, 'pooling', 'users', ['driver_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pooling', 'cars', ['car_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('pooling_users_user_id_fkey', 'pooling_users', type_='foreignkey')
    op.drop_constraint('pooling_users_pooling_id_fkey', 'pooling_users', type_='foreignkey')
    op.create_foreign_key(None, 'pooling_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pooling_users', 'pooling', ['pooling_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pooling_users', type_='foreignkey')
    op.drop_constraint(None, 'pooling_users', type_='foreignkey')
    op.create_foreign_key('pooling_users_pooling_id_fkey', 'pooling_users', 'pooling', ['pooling_id'], ['id'])
    op.create_foreign_key('pooling_users_user_id_fkey', 'pooling_users', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'pooling', type_='foreignkey')
    op.drop_constraint(None, 'pooling', type_='foreignkey')
    op.create_foreign_key('pooling_driver_id_fkey', 'pooling', 'users', ['driver_id'], ['id'])
    op.create_foreign_key('pooling_car_id_fkey', 'pooling', 'cars', ['car_id'], ['id'])
    op.drop_column('admins', 'active')
    # ### end Alembic commands ###
