"""models generation

Revision ID: 2910c978a1f4
Revises: 
Create Date: 2023-08-26 11:31:02.679615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2910c978a1f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('JWT_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('expired_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('confirmation_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('confirmation_code', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'used', name='codestatus'), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orig', sa.String(), nullable=False),
    sa.Column('params', sa.String(), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pooling_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('date_depart', sa.DateTime(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.Column('beg_dest', sa.Enum('Tunis', 'Beja', 'Kef', 'Sousse', 'Mahdia', 'Nabeul', 'Ariana', 'Ben_Arous', 'Manouba', 'Zaghouan', 'Bizerte', 'Jendouba', 'Sfax', 'Siliana', 'Monastir', 'Kairouan', 'Kasserine', 'Sidi_Bouzid', 'Gabes', 'Medenine', 'Tataouine', 'Gafsa', 'Tozeur', 'Kebeli', name='city'), nullable=False),
    sa.Column('end_dest', sa.Enum('Tunis', 'Beja', 'Kef', 'Sousse', 'Mahdia', 'Nabeul', 'Ariana', 'Ben_Arous', 'Manouba', 'Zaghouan', 'Bizerte', 'Jendouba', 'Sfax', 'Siliana', 'Monastir', 'Kairouan', 'Kasserine', 'Sidi_Bouzid', 'Gabes', 'Medenine', 'Tataouine', 'Gafsa', 'Tozeur', 'Kebeli', name='city'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reset_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('reset_code', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'used', name='codestatus'), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cin', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('age', sa.DateTime(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', name='gender'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cin'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_name', sa.String(), nullable=False),
    sa.Column('car_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pooling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('date_depart', sa.DateTime(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.Column('beg_dest', sa.Enum('Tunis', 'Beja', 'Kef', 'Sousse', 'Mahdia', 'Nabeul', 'Ariana', 'Ben_Arous', 'Manouba', 'Zaghouan', 'Bizerte', 'Jendouba', 'Sfax', 'Siliana', 'Monastir', 'Kairouan', 'Kasserine', 'Sidi_Bouzid', 'Gabes', 'Medenine', 'Tataouine', 'Gafsa', 'Tozeur', 'Kebeli', name='city'), nullable=False),
    sa.Column('end_dest', sa.Enum('Tunis', 'Beja', 'Kef', 'Sousse', 'Mahdia', 'Nabeul', 'Ariana', 'Ben_Arous', 'Manouba', 'Zaghouan', 'Bizerte', 'Jendouba', 'Sfax', 'Siliana', 'Monastir', 'Kairouan', 'Kasserine', 'Sidi_Bouzid', 'Gabes', 'Medenine', 'Tataouine', 'Gafsa', 'Tozeur', 'Kebeli', name='city'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pooling_users',
    sa.Column('pooling_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pooling_id'], ['pooling.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pooling_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pooling_users')
    op.drop_table('pooling')
    op.drop_table('reviews')
    op.drop_table('cars')
    op.drop_table('users')
    op.drop_table('reset_codes')
    op.drop_table('pooling_history')
    op.drop_table('errors')
    op.drop_table('confirmation_codes')
    op.drop_table('admins')
    op.drop_table('JWT_blacklist')
    # ### end Alembic commands ###
