from enum import Enum

class City(str, Enum):
    Tunis = "Tunis"
    Beja = "Beja"
    Kef = "Kef"
    Sousse = "Sousse"
    Mahdia = "Mahdia"
    Nabeul = "Nabeul"
    Ariana = "Ariana"
    Ben_Arous = "Ben Arous"
    Manouba = "Manouba"
    Zaghouan = "Zaghouan"
    Bizerte = "Bizerte"
    Jendouba = "Jendouba"
    Sfax = "Sfax"
    Siliana = "Siliana"
    Monastir = "Monastir"
    Kairouan = "Kairouan"
    Kasserine = "Kasserine"
    Sidi_Bouzid = "Sidi bouzid"
    Gabes = "Gabes"
    Medenine = "Medenine"
    Tataouine = "Tataouine"
    Gafsa = "Gafsa"
    Tozeur = "Tozeur"
    Kebeli = "Kebeli"